# Generated by Django 5.1.2 on 2024-10-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_rename_goal_goals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
    ]
