# Generated by Django 5.1.2 on 2024-10-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='slug',
        ),
    ]
