# Generated by Django 5.1.2 on 2024-10-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_goal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
